_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
            "3":
                - 2
                - 17
                - 19
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 10
image_size:
    value: 224
learning_rate:
    value: 0.01
network:
    value: resnet18
run_id:
    value: pznspfy4
